"""
Day 1: ETL Pipeline for Satellite Orbital Decay Prediction
============================================================
This module provides three core classes for ingesting satellite TLE data,
space weather data, and computing orbital propagation with environmental correlation.

Author: Generated by Zaid Khan 
Date: 2026-01-02
"""

import sqlite3
import requests
import pandas as pd
import numpy as np
from datetime import datetime, timezone
from typing import List, Dict, Optional, Tuple
from sgp4.api import Satrec, jday
from dataclasses import dataclass
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


# =============================================================================
# GOLDEN DATASET SATELLITE CATALOG
# =============================================================================
GOLDEN_DATASET = {
    # --- ZONE 1: THE "CANARIES" (High Sensitivity, <450km) ---
    "ISS": 25544,          # ~415 km. Huge area. CAUTION: Frequent reboost maneuvers.
    "Tiangong": 48274,     # ~390 km. The Chinese Space Station. Very high drag.

    # --- ZONE 2: THE "PURE DRAG" BASELINES (Medium Sensitivity, ~530km) ---
    "Hubble_HST": 20580,   # ~530 km. No engines. The perfect "Drag Anchor."
    "Fermi": 33053,        # ~500 km. Large solar panels, steady decay.

    # --- ZONE 3: THE "HEAVYWEIGHTS" (Upper LEO, ~700-800km) ---
    "Envisat": 27386,      # ~770 km. A massive 8-ton dead satellite. Tumbling.
    "Terra": 25994,        # ~700 km. Large Earth observation satellite.

    # --- ZONE 4: THE "TUMBLER" (Pure Ballistic Physics, No Attitude Control) ---
    "SL16_RocketBody": 22803,  # ~850 km. Zenit-2 rocket body. Perfect BC calibrator.

    # --- ZONE 5: THE CONTROL GROUP (No Drag, >2000km) ---
    "Vanguard_1": 5,       # ~3,000 km. Oldest debris. Should show effectively ZERO drop.
    "Vanguard_2": 11       # Kept for continuity
}


# =============================================================================
# CLASS 1: SpaceTrackIngestor
# =============================================================================
class SpaceTrackIngestor:
    """
    Ingests TLE (Two-Line Element) data from Space-Track.org API.
    
    Space-Track is the authoritative source for satellite tracking data
    maintained by the 18th Space Defense Squadron.
    
    Attributes:
        username: Space-Track account username
        password: Space-Track account password
        db_path: Path to SQLite database for storage
        session: Requests session with authentication cookie
    """
    
    BASE_URL = "https://www.space-track.org"
    LOGIN_URL = f"{BASE_URL}/ajaxauth/login"
    TLE_QUERY_URL = f"{BASE_URL}/basicspacedata/query/class/gp_history"
    
    def __init__(self, username: str, password: str, db_path: str = "satellite_data.db"):
        """
        Initialize the Space-Track ingester.
        
        Args:
            username: Space-Track.org username (requires free account)
            password: Space-Track.org password
            db_path: SQLite database file path
        """
        self.username = "mohdzaidk25@gmail.com"
        self.password = "ThisisspacetrackpassworD"
        self.db_path = "satellite_data.db"
        self.session = requests.Session()
        self._authenticated = False
        
        # Initialize database schema
        self._init_database()
    
    def _init_database(self) -> None:
        """Create the TLE storage table if it doesn't exist."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS tle_history (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    norad_id INTEGER NOT NULL,
                    satellite_name TEXT,
                    epoch_datetime TEXT NOT NULL,
                    tle_line1 TEXT NOT NULL,
                    tle_line2 TEXT NOT NULL,
                    mean_motion REAL,
                    eccentricity REAL,
                    inclination REAL,
                    bstar REAL,
                    ingestion_timestamp TEXT DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(norad_id, epoch_datetime)
                )
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_tle_norad_epoch 
                ON tle_history(norad_id, epoch_datetime)
            """)
            conn.commit()
        logger.info(f"TLE database initialized at {self.db_path}")
    
    def authenticate(self) -> bool:
        """
        Authenticate with Space-Track.org API.
        
        Returns:
            True if authentication successful, False otherwise
        """
        try:
            response = self.session.post(
                self.LOGIN_URL,
                data={
                    'identity': self.username,
                    'password': self.password
                },
                timeout=30
            )
            
            if response.status_code == 200 and 'Login' not in response.text:
                self._authenticated = True
                logger.info("Successfully authenticated with Space-Track.org")
                return True
            else:
                logger.error("Authentication failed - check credentials")
                return False
                
        except requests.RequestException as e:
            logger.error(f"Authentication request failed: {e}")
            return False
    
    def _check_cache(self, norad_id: int) -> int:
        """
        Check if TLE data exists in local cache.
        
        CRITICAL: Space-Track has strict "1/lifetime" download limit for GP_HISTORY.
        This method MUST be called before any API request to prevent bans.
        
        Args:
            norad_id: NORAD catalog ID
            
        Returns:
            Count of cached TLE records for this satellite
        """
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute(
                "SELECT COUNT(*) FROM tle_history WHERE norad_id = ?", 
                (norad_id,)
            )
            count = cursor.fetchone()[0]
        return count
    
    def fetch_history(
        self, 
        norad_id: int, 
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        limit: int = 10000,
        force_refresh: bool = False
    ) -> pd.DataFrame:
        """
        Fetch historical TLE data for a specific satellite with CACHE-FIRST logic.
        
        ⚠️ CRITICAL RATE LIMIT PROTECTION:
        Space-Track has a strict "1/lifetime" download limit for GP_HISTORY.
        This method checks local cache BEFORE making any API calls.
        
        Cache Logic:
        1. Query local SQLite: SELECT COUNT(*) FROM tle_history WHERE norad_id = ?
        2. If count > 0: Return cached data (no API call)
        3. If count == 0: Call Space-Track API, save immediately, then return
        
        Args:
            norad_id: NORAD catalog ID (e.g., 1361 for LCS-1)
            start_date: Start date in YYYY-MM-DD format (default: 1 year ago)
            end_date: End date in YYYY-MM-DD format (default: today)
            limit: Maximum number of TLEs to fetch
            force_refresh: ⚠️ DANGER! Set True only if you're certain you won't get banned
            
        Returns:
            DataFrame with TLE history (from cache or API)
        """
        # =====================================================================
        # CACHE-FIRST CHECK - CRITICAL FOR RATE LIMIT PROTECTION
        # =====================================================================
        cached_count = self._check_cache(norad_id)
        
        if cached_count > 0 and not force_refresh:
            print(f"    [CACHE HIT] Found {cached_count} TLE records for NORAD ID {norad_id} locally. Skipping download.")
            logger.info(f"[CACHE HIT] Returning {cached_count} cached TLEs for NORAD ID {norad_id}")
            return self.get_stored_tles(norad_id)
        
        if force_refresh:
            logger.warning(f"⚠️ FORCE REFRESH enabled for NORAD ID {norad_id} - this may trigger rate limits!")
            print(f"    ⚠️ WARNING: Force refresh enabled. This may trigger Space-Track rate limits!")
        
        # =====================================================================
        # NO CACHE - PROCEED WITH API CALL
        # =====================================================================
        print(f"    [CACHE MISS] No local data for NORAD ID {norad_id}. Downloading from Space-Track...")
        
        if not self._authenticated:
            if not self.authenticate():
                raise ConnectionError("Failed to authenticate with Space-Track")
        
        # Default date range: last year
        if end_date is None:
            end_date = datetime.now(timezone.utc).strftime('%Y-%m-%d')
        if start_date is None:
            start_dt = datetime.now(timezone.utc).replace(year=datetime.now().year - 1)
            start_date = start_dt.strftime('%Y-%m-%d')
        
        # Build query URL
        query_url = (
            f"{self.TLE_QUERY_URL}"
            f"/NORAD_CAT_ID/{norad_id}"
            f"/EPOCH/{start_date}--{end_date}"
            f"/orderby/EPOCH%20asc"
            f"/limit/{limit}"
            f"/format/json"
        )
        
        logger.info(f"Fetching TLE history for NORAD ID {norad_id} from Space-Track API")
        
        try:
            response = self.session.get(query_url, timeout=60)
            response.raise_for_status()
            
            data = response.json()
            
            if not data:
                logger.warning(f"No TLE data found for NORAD ID {norad_id}")
                return pd.DataFrame()
            
            # Convert to DataFrame using pandas for speed
            df = pd.DataFrame(data)
            
            # IMMEDIATELY store to database to prevent needing to re-download
            records_stored = self._store_tles(df, norad_id)
            logger.info(f"✓ Stored {records_stored} TLE records for NORAD ID {norad_id}")
            print(f"    ✓ Downloaded and cached {records_stored} TLE records")
            
            return df
            
        except requests.RequestException as e:
            logger.error(f"Failed to fetch TLE data: {e}")
            print(f"    ✗ API request failed: {e}")
            print(f"    💡 TIP: Use load_from_file() to manually import TLE data")
            raise
    
    def load_from_file(
        self, 
        file_path: str, 
        norad_id: int,
        file_format: str = "auto"
    ) -> pd.DataFrame:
        """
        Load TLE data from a local file (JSON or TXT format).
        
        ⚠️ BACKUP PLAN: Use this if the Space-Track API fails or rate limits you.
        You can manually download bulk ZIPs from:
        https://www.space-track.org/documentation#/api
        
        Supported formats:
        - JSON: Direct export from Space-Track API
        - TXT: Standard 3-line TLE format (name + line1 + line2)
        
        Args:
            file_path: Path to the TLE file (.json or .txt)
            norad_id: NORAD catalog ID for these TLEs
            file_format: "json", "txt", or "auto" (detect from extension)
            
        Returns:
            DataFrame with loaded TLE data
        """
        import os
        import json
        
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"TLE file not found: {file_path}")
        
        # Auto-detect format
        if file_format == "auto":
            ext = os.path.splitext(file_path)[1].lower()
            if ext == ".json":
                file_format = "json"
            elif ext in [".txt", ".tle"]:
                file_format = "txt"
            else:
                raise ValueError(f"Unknown file extension: {ext}. Use file_format='json' or 'txt'")
        
        logger.info(f"Loading TLE data from {file_path} (format: {file_format})")
        print(f"    📁 Loading TLE data from: {file_path}")
        
        if file_format == "json":
            return self._load_from_json(file_path, norad_id)
        elif file_format == "txt":
            return self._load_from_txt(file_path, norad_id)
        else:
            raise ValueError(f"Unsupported format: {file_format}")
    
    def _load_from_json(self, file_path: str, norad_id: int) -> pd.DataFrame:
        """
        Load TLEs from JSON file (Space-Track export format).
        
        Args:
            file_path: Path to JSON file
            norad_id: NORAD catalog ID
            
        Returns:
            DataFrame with TLE data
        """
        import json
        
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        if not data:
            logger.warning(f"Empty JSON file: {file_path}")
            return pd.DataFrame()
        
        # Handle both list format and single object
        if isinstance(data, dict):
            data = [data]
        
        df = pd.DataFrame(data)
        
        # Store to database
        records_stored = self._store_tles(df, norad_id)
        logger.info(f"Loaded and stored {records_stored} TLEs from JSON")
        print(f"    ✓ Loaded {records_stored} TLE records from JSON")
        
        return df
    
    def _load_from_txt(self, file_path: str, norad_id: int) -> pd.DataFrame:
        """
        Load TLEs from TXT file (standard 3-line TLE format).
        
        Expected format (each TLE is 3 lines):
        SATELLITE NAME
        1 25544U 98067A   21275.51234567  .00001234  00000-0  12345-4 0  9991
        2 25544  51.6456 123.4567 0001234  12.3456 347.6543 15.48919755123456
        
        Args:
            file_path: Path to TXT file
            norad_id: NORAD catalog ID
            
        Returns:
            DataFrame with TLE data
        """
        records = []
        
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = [line.strip() for line in f.readlines() if line.strip()]
        
        # Process in groups of 3 lines
        i = 0
        while i < len(lines):
            # Check if this looks like a TLE set
            if i + 2 < len(lines):
                line0 = lines[i]      # Satellite name
                line1 = lines[i + 1]  # TLE line 1
                line2 = lines[i + 2]  # TLE line 2
                
                # Validate TLE format (line 1 starts with "1 ", line 2 starts with "2 ")
                if line1.startswith("1 ") and line2.startswith("2 "):
                    # Extract epoch from line 1 (columns 18-32)
                    try:
                        epoch_str = line1[18:32].strip()
                        # Parse TLE epoch format: YYDDD.DDDDDDDD
                        year_2digit = int(epoch_str[:2])
                        day_fraction = float(epoch_str[2:])
                        
                        # Convert 2-digit year (57-99 = 1900s, 00-56 = 2000s)
                        if year_2digit >= 57:
                            year = 1900 + year_2digit
                        else:
                            year = 2000 + year_2digit
                        
                        # Convert day of year to datetime
                        epoch_dt = datetime(year, 1, 1, tzinfo=timezone.utc) + pd.Timedelta(days=day_fraction - 1)
                        
                        records.append({
                            'OBJECT_NAME': line0,
                            'TLE_LINE1': line1,
                            'TLE_LINE2': line2,
                            'EPOCH': epoch_dt.isoformat(),
                            'NORAD_CAT_ID': norad_id
                        })
                        
                        i += 3
                        continue
                        
                    except (ValueError, IndexError) as e:
                        logger.warning(f"Failed to parse TLE at line {i}: {e}")
            
            i += 1
        
        if not records:
            logger.warning(f"No valid TLEs found in {file_path}")
            return pd.DataFrame()
        
        df = pd.DataFrame(records)
        
        # Store to database
        records_stored = self._store_tles(df, norad_id)
        logger.info(f"Loaded and stored {records_stored} TLEs from TXT")
        print(f"    ✓ Loaded {records_stored} TLE records from TXT file")
        
        return df
    
    def _store_tles(self, df: pd.DataFrame, norad_id: int) -> int:
        """
        Store TLE records to SQLite database.
        
        Args:
            df: DataFrame with TLE data from Space-Track or file
            norad_id: NORAD catalog ID
            
        Returns:
            Number of records inserted
        """
        records_inserted = 0
        
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            for _, row in df.iterrows():
                try:
                    cursor.execute("""
                        INSERT OR IGNORE INTO tle_history 
                        (norad_id, satellite_name, epoch_datetime, tle_line1, tle_line2,
                         mean_motion, eccentricity, inclination, bstar)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, (
                        norad_id,
                        row.get('OBJECT_NAME', ''),
                        row.get('EPOCH', ''),
                        row.get('TLE_LINE1', ''),
                        row.get('TLE_LINE2', ''),
                        float(row.get('MEAN_MOTION', 0)) if pd.notna(row.get('MEAN_MOTION')) else 0.0,
                        float(row.get('ECCENTRICITY', 0)) if pd.notna(row.get('ECCENTRICITY')) else 0.0,
                        float(row.get('INCLINATION', 0)) if pd.notna(row.get('INCLINATION')) else 0.0,
                        float(row.get('BSTAR', 0)) if pd.notna(row.get('BSTAR')) else 0.0
                    ))
                    
                    if cursor.rowcount > 0:
                        records_inserted += 1
                        
                except (sqlite3.Error, ValueError) as e:
                    logger.warning(f"Failed to insert TLE record: {e}")
                    
            conn.commit()
        
        return records_inserted
    
    def get_stored_tles(self, norad_id: int) -> pd.DataFrame:
        """
        Retrieve TLEs from local SQLite database.
        
        Args:
            norad_id: NORAD catalog ID
            
        Returns:
            DataFrame with stored TLE history
        """
        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT * FROM tle_history 
                WHERE norad_id = ? 
                ORDER BY epoch_datetime ASC
            """
            return pd.read_sql_query(query, conn, params=(norad_id,))
    
    def get_cache_status(self) -> pd.DataFrame:
        """
        Get cache status for all satellites in the database.
        
        Returns:
            DataFrame with NORAD ID, satellite name, and record count
        """
        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT 
                    norad_id,
                    satellite_name,
                    COUNT(*) as record_count,
                    MIN(epoch_datetime) as earliest_epoch,
                    MAX(epoch_datetime) as latest_epoch
                FROM tle_history
                GROUP BY norad_id
                ORDER BY norad_id
            """
            return pd.read_sql_query(query, conn)
    
    def fetch_tle_golden_epoch(
        self,
        norad_id: int,
        start_year: int = 2014,
        end_year: int = None,
        force_refresh: bool = False
    ) -> int:
        """
        Fetch TLEs for the "Golden Epoch" (2014-present) using yearly chunks.
        
        Space-Track API times out on large date ranges (11+ years).
        This method fetches year-by-year to avoid timeout.
        
        Args:
            norad_id: NORAD catalog ID
            start_year: First year to fetch (default: 2014)
            end_year: Last year to fetch (default: current year)
            force_refresh: If True, re-download even if cached
            
        Returns:
            Total number of TLE records fetched
        """
        import time
        
        if end_year is None:
            end_year = datetime.now().year
        
        total_records = 0
        
        # Check existing cache first
        if not force_refresh:
            cached_count = self._check_cache(norad_id)
            if cached_count > 0:
                print(f"    [CACHE HIT] Found {cached_count} TLEs for NORAD {norad_id}. Use force_refresh=True to re-download.")
                return cached_count
        
        # Authenticate if needed
        if not self._authenticated:
            if not self.authenticate():
                raise ConnectionError("Failed to authenticate with Space-Track")
        
        print(f"    🔄 Fetching TLEs for NORAD {norad_id} ({start_year}-{end_year})...")
        
        for year in range(start_year, end_year + 1):
            start_date = f"{year}-01-01"
            end_date = f"{year}-12-31"
            
            # Build query URL
            query_url = (
                f"{self.TLE_QUERY_URL}"
                f"/NORAD_CAT_ID/{norad_id}"
                f"/EPOCH/{start_date}--{end_date}"
                f"/orderby/EPOCH%20asc"
                f"/limit/10000"
                f"/format/json"
            )
            
            try:
                response = self.session.get(query_url, timeout=120)
                response.raise_for_status()
                
                data = response.json()
                
                if data:
                    df = pd.DataFrame(data)
                    records_stored = self._store_tles(df, norad_id)
                    total_records += records_stored
                    print(f"       ✓ {year}: {records_stored} TLEs")
                else:
                    print(f"       - {year}: No data")
                
                # Small delay to avoid rate limiting
                time.sleep(1.5)
                
            except requests.RequestException as e:
                logger.warning(f"Failed to fetch TLEs for {year}: {e}")
                print(f"       ✗ {year}: API error - {e}")
                time.sleep(3)  # Longer delay on error
        
        logger.info(f"Fetched {total_records} total TLEs for NORAD {norad_id} ({start_year}-{end_year})")
        print(f"    ✅ Total: {total_records} TLEs for NORAD {norad_id}")
        
        return total_records


# =============================================================================
# CLASS 2: SpaceWeatherIngestor
# =============================================================================
class SpaceWeatherIngestor:
    """
    Ingests space weather data from NOAA Space Weather Prediction Center.
    
    The Kp index measures global geomagnetic activity on a 0-9 scale.
    Higher Kp values indicate increased atmospheric drag affecting satellites.
    
    Data Sources:
        - Live: NOAA SWPC JSON API (current implementation)
        - Historical: NOAA Annual Archives for training datasets
    
    Attributes:
        db_path: Path to SQLite database for storage
    """
    
    # LIVE DATA URL - Current planetary K-index
    LIVE_KP_URL = "https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json"
    
    # TODO: For training ML models, swap to NOAA Annual Archives:
    # ARCHIVE_URL_TEMPLATE = "https://www.ngdc.noaa.gov/stp/GEOMAG/kp_ap/kp_data/{year}/Kp_ap_{year}.txt"
    # Format: wget https://www.ngdc.noaa.gov/stp/GEOMAG/kp_ap/kp_data/2023/Kp_ap_2023.txt
    # Parse fixed-width format: YYYY MM DD Kp1 Kp2 Kp3 Kp4 Kp5 Kp6 Kp7 Kp8 Ap
    
    def __init__(self, db_path: str = "satellite_data.db"):
        """
        Initialize the Space Weather ingester.
        
        Args:
            db_path: SQLite database file path
        """
        self.db_path = db_path
        self._init_database()
    
    def _init_database(self) -> None:
        """Create the space weather storage tables if they don't exist."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            # Table 1: Planetary K-index (Geomagnetic Storms)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS space_weather (
                    time_tag TEXT PRIMARY KEY,
                    kp REAL NOT NULL,
                    kp_fraction REAL,
                    a_running REAL,
                    station_count INTEGER,
                    ingestion_timestamp TEXT DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_space_weather_time 
                ON space_weather(time_tag)
            """)
            
            # Table 2: Solar Flux F10.7 (Ultraviolet Emissions) [NEW]
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS solar_flux (
                    date_tag TEXT PRIMARY KEY,
                    f107_adj REAL,
                    f107_obs REAL,
                    ingestion_timestamp TEXT DEFAULT CURRENT_TIMESTAMP
                )
            """)
            
            conn.commit()
        logger.info(f"Space weather database tables initialized at {self.db_path}")
    
    def fetch_kp_data(self) -> pd.DataFrame:
        """
        Fetch current Kp index data from NOAA SWPC.
        
        The JSON response format:
            - First row: Header ["time_tag", "Kp", ...]
            - Subsequent rows: Data values
        
        Returns:
            DataFrame with Kp index data, also stored to SQLite
        """
        logger.info("Fetching Kp index data from NOAA SWPC")
        
        try:
            # Use pandas.read_json for optimized parsing
            response = requests.get(self.LIVE_KP_URL, timeout=30)
            response.raise_for_status()
            
            raw_data = response.json()
            
            if not raw_data or len(raw_data) < 2:
                logger.warning("No Kp data received from NOAA")
                return pd.DataFrame()
            
            # Parse header dynamically (first row contains column names)
            header = raw_data[0]
            data_rows = raw_data[1:]
            
            # Create DataFrame with dynamic header
            df = pd.DataFrame(data_rows, columns=header)
            
            # Convert time_tag to UTC datetime
            df['time_tag'] = pd.to_datetime(df['time_tag'], utc=True)
            
            # Convert Kp to numeric (handles string values like "3.33")
            df['Kp'] = pd.to_numeric(df['Kp'], errors='coerce')
            
            records_stored = self._store_kp_data(df)
            logger.info(f"Stored {records_stored} Kp index records")
            
            return df
            
        except requests.RequestException as e:
            logger.error(f"Failed to fetch Kp data: {e}")
            return pd.DataFrame()
        except (ValueError, KeyError) as e:
            logger.error(f"Failed to parse Kp data: {e}")
            return pd.DataFrame()

    def fetch_solar_flux(self) -> None:
        """
        Fetch F10.7 Solar Flux data from NOAA SWPC. [NEW]
        
        F10.7 cm Radio Flux is a proxy for Extreme Ultraviolet (EUV) radiation
        that heats the thermosphere.
        
        URL: https://services.swpc.noaa.gov/json/f107_cm_flux.json
        """
        FLUX_URL = "https://services.swpc.noaa.gov/json/f107_cm_flux.json"
        logger.info("Fetching F10.7 Solar Flux data from NOAA SWPC")
        
        try:
            response = requests.get(FLUX_URL, timeout=30)
            response.raise_for_status()
            data = response.json()
            
            # Process list of dictionaries
            processed_records = []
            seen_dates = set()
            
            # Iterate in reverse to keep latest entry per date (if duplicates exist)
            for record in reversed(data):
                try:
                    # Parse date (format: "2023-10-25T12:00:00")
                    # We only care about the Date (Daily resolution)
                    dt = datetime.fromisoformat(record['time_tag'])
                    date_key = dt.strftime('%Y-%m-%d')
                    
                    if date_key in seen_dates:
                        continue
                        
                    flux_val = float(record['flux'])
                    
                    processed_records.append({
                        'date_tag': date_key,
                        'f107_adj': flux_val, # Assuming adjusted flux
                        'f107_obs': flux_val  # Saving same value for now
                    })
                    seen_dates.add(date_key)
                    
                except (ValueError, KeyError) as e:
                    continue
            
            if processed_records:
                df_flux = pd.DataFrame(processed_records)
                self._store_solar_flux(df_flux)
            else:
                logger.warning("No valid Solar Flux records found")
                
        except Exception as e:
            logger.error(f"Failed to fetch Solar Flux data: {e}")

    def _store_solar_flux(self, df: pd.DataFrame) -> int:
        """Store Solar Flux records to SQLite. [NEW]"""
        inserted = 0
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            for _, row in df.iterrows():
                try:
                    cursor.execute("""
                        INSERT OR REPLACE INTO solar_flux 
                        (date_tag, f107_adj, f107_obs)
                        VALUES (?, ?, ?)
                    """, (row['date_tag'], row['f107_adj'], row['f107_obs']))
                    inserted += 1
                except sqlite3.Error:
                    pass
            conn.commit()
        logger.info(f"Stored {inserted} Solar Flux records")
        return inserted

    def fetch_historical_kp_and_f107(self, start_year: int = 2014, end_year: int = 2026) -> dict:
        """
        Fetch historical Kp AND F10.7 data from GFZ Potsdam archive. [UPGRADED]
        
        This provides both Kp and F10.7 solar flux data for training ML models
        across a full solar cycle (Solar Minimum ~2019-2020 to Solar Maximum ~2024-2025).
        
        Data Source: GFZ Potsdam Master File (since 1932)
        URL: https://www-app3.gfz-potsdam.de/kp_index/Kp_ap_Ap_SN_F107_since_1932.txt
        
        Args:
            start_year: First year to include (default: 2014)
            end_year: Last year to include (default: 2026)
            
        Returns:
            Dict with 'kp_records' and 'f107_records' counts
        """
        # =====================================================================
        # CACHE-FIRST CHECK - Avoid unnecessary API calls
        # =====================================================================
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            # Check if we already have Kp data for this range
            cursor.execute("""
                SELECT COUNT(*) FROM space_weather 
                WHERE time_tag >= ? AND time_tag < ?
            """, (f"{start_year}-01-01", f"{end_year + 1}-01-01"))
            kp_count = cursor.fetchone()[0]
            
            # Check if we already have F10.7 data for this range
            cursor.execute("""
                SELECT COUNT(*) FROM solar_flux 
                WHERE date_tag >= ? AND date_tag < ?
            """, (f"{start_year}-01-01", f"{end_year + 1}-01-01"))
            f107_count = cursor.fetchone()[0]
        
        if kp_count > 0 and f107_count > 0:
            print(f"    [CACHE HIT] Found {kp_count} Kp records and {f107_count} F10.7 records for {start_year}-{end_year}.")
            print(f"    └── Skipping download. Use force_refresh=True to re-download.")
            logger.info(f"[CACHE HIT] Kp: {kp_count} records, F10.7: {f107_count} records")
            return {'kp_records': kp_count, 'f107_records': f107_count}
        
        # =====================================================================
        # NO CACHE - PROCEED WITH DOWNLOAD
        # =====================================================================
        MASTER_URL = "https://www-app3.gfz-potsdam.de/kp_index/Kp_ap_Ap_SN_F107_since_1932.txt"
        total_kp_stored = 0
        total_f107_stored = 0
        
        logger.info(f"Fetching historical Kp + F10.7 data from GFZ master file ({start_year}-{end_year})")
        print(f"    ↳ Downloading Kp + F10.7 archive from GFZ Potsdam...")
        
        try:
            response = requests.get(MASTER_URL, timeout=120)
            
            if response.status_code != 200:
                logger.error(f"Failed to fetch master file: HTTP {response.status_code}")
                return {'kp_records': 0, 'f107_records': 0}
            
            print(f"    ✓ Downloaded {len(response.text) // 1024} KB of historical data")
            
            # Parse the fixed-width format file
            kp_records = []
            f107_records = []
            
            for line in response.text.strip().split('\n'):
                # Skip header/comment lines
                if line.startswith('#') or not line.strip():
                    continue
                
                try:
                    parts = line.split()
                    if len(parts) < 20:  # Need at least 20 columns for F10.7obs
                        continue
                    
                    # Format: YYYY MM DD days days_m Bsr dB Kp1 Kp2 Kp3 Kp4 Kp5 Kp6 Kp7 Kp8 Ap Cp C9 Isr F107obs F107adj
                    # Index:    0   1  2   3     4     5  6   7   8   9  10  11  12  13  14  15 16 17  18   19      20
                    yr = int(parts[0])
                    month = int(parts[1])
                    day = int(parts[2])
                    
                    # Filter by year range
                    if yr < start_year or yr > end_year:
                        continue
                    
                    # === PARSE KP VALUES (indices 7-14) ===
                    kp_values = []
                    for i in range(7, min(15, len(parts))):
                        try:
                            kp_val = float(parts[i])
                            if kp_val >= 0:  # Valid Kp (negative = missing)
                                kp_values.append(kp_val)
                        except ValueError:
                            continue
                    
                    if kp_values:
                        # Create 3-hourly records (00:00, 03:00, 06:00, etc.)
                        for idx, kp in enumerate(kp_values):
                            hour = idx * 3
                            time_tag = f"{yr:04d}-{month:02d}-{day:02d}T{hour:02d}:00:00+00:00"
                            kp_records.append({
                                'time_tag': time_tag,
                                'kp': kp,
                                'kp_fraction': kp - int(kp),
                                'a_running': None,
                                'station_count': None
                            })
                    
                    # === PARSE F10.7 VALUES (Indices 25-26, previously thought 19-20) ===
                    # Structure: Date(0-2) Meta(3-6) Kp(7-14) ap(15-22) Ap(23) SN(24) F10.7obs(25) F10.7adj(26)
                    try:
                        f107_obs = float(parts[25]) if len(parts) > 25 else None
                        f107_adj = float(parts[26]) if len(parts) > 26 else None
                        
                        # Quality filter: F10.7 should be in realistic range (50-400 SFU)
                        # Negative values indicate missing data
                        if f107_obs and f107_obs > 0 and 50 <= f107_obs <= 400:
                            date_tag = f"{yr:04d}-{month:02d}-{day:02d}"
                            f107_records.append({
                                'date_tag': date_tag,
                                'f107_obs': f107_obs,
                                'f107_adj': f107_adj if f107_adj and f107_adj > 0 else f107_obs
                            })
                    except (ValueError, IndexError):
                        pass
                    
                except (ValueError, IndexError):
                    continue
            
            # Store Kp data
            if kp_records:
                df_kp = pd.DataFrame(kp_records)
                total_kp_stored = self._store_kp_data(df_kp)
                print(f"    ✓ Stored {total_kp_stored} Kp records ({start_year}-{end_year})")
            
            # Store F10.7 data
            if f107_records:
                df_f107 = pd.DataFrame(f107_records)
                total_f107_stored = self._store_f107_data(df_f107)
                print(f"    ✓ Stored {total_f107_stored} F10.7 records ({start_year}-{end_year})")
                
        except requests.RequestException as e:
            logger.error(f"Failed to fetch historical data: {e}")
        
        logger.info(f"Total records stored - Kp: {total_kp_stored}, F10.7: {total_f107_stored}")
        return {'kp_records': total_kp_stored, 'f107_records': total_f107_stored}
    
    # Keep old method name for backwards compatibility
    def fetch_historical_kp(self, start_year: int = 2014, end_year: int = 2026) -> int:
        """
        Backwards compatibility wrapper for fetch_historical_kp_and_f107.
        Returns only Kp record count.
        """
        result = self.fetch_historical_kp_and_f107(start_year, end_year)
        return result['kp_records']
    
    
    def _store_kp_data(self, df: pd.DataFrame) -> int:
        """
        Store Kp index records to SQLite database.
        
        Uses composite primary key (timestamp) to prevent duplicates.
        
        Args:
            df: DataFrame with Kp index data
            
        Returns:
            Number of records inserted
        """
        records_inserted = 0
        
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            for _, row in df.iterrows():
                try:
                    # Convert timestamp to ISO format for storage
                    time_tag = row['time_tag'].isoformat() if hasattr(row['time_tag'], 'isoformat') else str(row['time_tag'])
                    
                    cursor.execute("""
                        INSERT OR REPLACE INTO space_weather 
                        (time_tag, kp, kp_fraction, a_running, station_count)
                        VALUES (?, ?, ?, ?, ?)
                    """, (
                        time_tag,
                        float(row['kp']) if pd.notna(row['kp']) else None,
                        float(row.get('kp_fraction', 0)) if pd.notna(row.get('kp_fraction')) else None,
                        float(row.get('a_running')) if pd.notna(row.get('a_running')) else None,
                        int(row.get('station_count')) if pd.notna(row.get('station_count')) else None
                    ))
                    
                    if cursor.rowcount > 0:
                        records_inserted += 1
                        
                except (sqlite3.Error, ValueError) as e:
                    logger.warning(f"Failed to insert Kp record: {e}")
                    
            conn.commit()
        
        return records_inserted
    
    def _store_f107_data(self, df: pd.DataFrame) -> int:
        """
        Store F10.7 solar flux records to SQLite database. [NEW]
        
        Uses date_tag as primary key to prevent duplicates.
        Applies data integrity filters: 50 <= F10.7 <= 400 SFU
        
        Args:
            df: DataFrame with columns ['date_tag', 'f107_obs', 'f107_adj']
            
        Returns:
            Number of records inserted
        """
        records_inserted = 0
        
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            for _, row in df.iterrows():
                try:
                    f107_obs = float(row['f107_obs']) if pd.notna(row['f107_obs']) else None
                    f107_adj = float(row['f107_adj']) if pd.notna(row['f107_adj']) else None
                    
                    # Quality filter: Skip invalid values
                    if not f107_obs or f107_obs < 50 or f107_obs > 400:
                        continue
                    
                    cursor.execute("""
                        INSERT OR REPLACE INTO solar_flux 
                        (date_tag, f107_obs, f107_adj)
                        VALUES (?, ?, ?)
                    """, (
                        str(row['date_tag']),
                        f107_obs,
                        f107_adj if f107_adj else f107_obs  # Use obs if adj is missing
                    ))
                    
                    if cursor.rowcount > 0:
                        records_inserted += 1
                        
                except (sqlite3.Error, ValueError) as e:
                    logger.warning(f"Failed to insert F10.7 record: {e}")
                    
            conn.commit()
        
        logger.info(f"Stored {records_inserted} F10.7 solar flux records")
        return records_inserted
    
    def get_stored_kp_data(
        self, 
        start_date: Optional[str] = None, 
        end_date: Optional[str] = None
    ) -> pd.DataFrame:
        """
        Retrieve Kp data from local SQLite database.
        
        Args:
            start_date: Start date filter (ISO format)
            end_date: End date filter (ISO format)
            
        Returns:
            DataFrame with stored Kp history
        """
        with sqlite3.connect(self.db_path) as conn:
            query = "SELECT * FROM space_weather"
            params = []
            
            conditions = []
            if start_date:
                conditions.append("time_tag >= ?")
                params.append(start_date)
            if end_date:
                conditions.append("time_tag <= ?")
                params.append(end_date)
                
            if conditions:
                query += " WHERE " + " AND ".join(conditions)
            
            query += " ORDER BY time_tag ASC"
            
            return pd.read_sql_query(query, conn, params=params)
    
    def get_daily_kp_summary(self) -> pd.DataFrame:
        """
        Get daily aggregated Kp statistics.
        
        Returns:
            DataFrame with daily Kp mean, max, and sum
        """
        with sqlite3.connect(self.db_path) as conn:
            query = """
                SELECT 
                    DATE(time_tag) as date,
                    AVG(kp) as kp_mean,
                    MAX(kp) as kp_max,
                    SUM(kp) as kp_sum,
                    COUNT(*) as readings
                FROM space_weather
                GROUP BY DATE(time_tag)
                ORDER BY date ASC
            """
            return pd.read_sql_query(query, conn)


# =============================================================================
# CLASS 3: OrbitalPropagator
# =============================================================================
class OrbitalPropagator:
    """
    Propagates satellite orbits using SGP4 and correlates with space weather.
    
    SGP4 (Simplified General Perturbations 4) is the standard algorithm
    for predicting satellite positions from TLE elements.
    
    Attributes:
        db_path: Path to SQLite database with TLE and Kp data
    """
    
    # Earth's equatorial radius in kilometers
    EARTH_RADIUS_KM = 6378.137
    
    def __init__(self, db_path: str = "satellite_data.db"):
        """
        Initialize the Orbital Propagator.
        
        Args:
            db_path: SQLite database file path with TLE and Kp data
        """
        self.db_path = db_path
    
    def _parse_tle_to_satrec(self, tle_line1: str, tle_line2: str) -> Optional[Satrec]:
        """
        Parse TLE lines into SGP4 Satrec object.
        
        Args:
            tle_line1: First line of TLE
            tle_line2: Second line of TLE
            
        Returns:
            Satrec object for propagation, or None if parsing fails
        """
        try:
            satellite = Satrec.twoline2rv(tle_line1, tle_line2)
            return satellite
        except Exception as e:
            logger.warning(f"Failed to parse TLE: {e}")
            return None
    
    def calculate_altitude(
        self, 
        satellite: Satrec, 
        dt: datetime
    ) -> Optional[float]:
        """
        Calculate satellite altitude at a specific datetime.
        
        Uses SGP4 propagation to get position vector, then calculates
        distance from Earth center minus Earth radius.
        
        Args:
            satellite: Satrec object from TLE
            dt: Datetime for position calculation
            
        Returns:
            Altitude in kilometers, or None if propagation fails
        """
        try:
            # Convert datetime to Julian date
            jd, fr = jday(
                dt.year, dt.month, dt.day,
                dt.hour, dt.minute, dt.second + dt.microsecond / 1e6
            )
            
            # Propagate to get position and velocity
            error_code, position, velocity = satellite.sgp4(jd, fr)
            
            if error_code != 0:
                return None
            
            # Calculate distance from Earth center
            x, y, z = position
            distance_km = np.sqrt(x**2 + y**2 + z**2)
            
            # Altitude = distance - Earth radius
            altitude_km = distance_km - self.EARTH_RADIUS_KM
            
            return altitude_km
            
        except Exception as e:
            logger.warning(f"Altitude calculation failed: {e}")
            return None
    
    def propagate_with_weather(
        self, 
        norad_id: int,
        sample_interval_hours: int = 24
    ) -> pd.DataFrame:
        """
        Generate combined orbital and space weather dataset.
        
        This method:
        1. Retrieves TLEs for the satellite
        2. Retrieves Kp index data
        3. For each TLE epoch, calculates altitude
        4. Joins with closest Kp reading
        5. Computes daily altitude drop
        
        Args:
            norad_id: NORAD catalog ID
            sample_interval_hours: Interval for sampling (default: daily)
            
        Returns:
            DataFrame with columns [Date, Altitude, Kp_Index, Daily_Drop]
        """
        logger.info(f"Propagating orbit for NORAD ID {norad_id}")
        
        # Load TLE data
        with sqlite3.connect(self.db_path) as conn:
            tle_df = pd.read_sql_query(
                """
                SELECT epoch_datetime, tle_line1, tle_line2 
                FROM tle_history 
                WHERE norad_id = ? 
                ORDER BY epoch_datetime ASC
                """,
                conn,
                params=(norad_id,)
            )
            
            kp_df = pd.read_sql_query(
                """
                SELECT time_tag, kp 
                FROM space_weather 
                ORDER BY time_tag ASC
                """,
                conn
            )
        
        if tle_df.empty:
            logger.warning(f"No TLE data found for NORAD ID {norad_id}")
            return pd.DataFrame(columns=['Date', 'Altitude', 'Kp_Index', 'Daily_Drop'])
        
        # Convert timestamps
        tle_df['epoch_datetime'] = pd.to_datetime(tle_df['epoch_datetime'], utc=True)
        
        if not kp_df.empty:
            kp_df['time_tag'] = pd.to_datetime(kp_df['time_tag'], utc=True)
        
        # Vectorized altitude calculation
        results = []
        
        for idx, row in tle_df.iterrows():
            try:
                satellite = self._parse_tle_to_satrec(row['tle_line1'], row['tle_line2'])
                
                if satellite is None:
                    continue
                
                # EXTRACT MEAN ELEMENTS (STABLE PURE DRAG) [NEW]
                # Instead of instantaneous SGP4 propagation (which includes oscillation noise),
                # we use the Mean Motion directly from the TLE logic.
                
                # Constants
                MU = 398600.4418  # Earth Gravitational Parameter (km^3/s^2)
                EARTH_RADIUS_KM = 6378.137
                
                # 1. Get Mean Motion (no_kozai) in radians/minute
                mean_motion_rad_min = satellite.model.no_kozai
                
                # 2. Convert to radians/second
                mean_motion_rad_sec = mean_motion_rad_min / 60.0
                
                # 3. Calculate Semi-Major Axis (km) -> (mu / n^2)^(1/3)
                if mean_motion_rad_sec > 0:
                    semi_major_axis_km = (MU / (mean_motion_rad_sec ** 2)) ** (1/3)
                else:
                    continue
                
                # 4. Calculate Mean Altitude (SMA - Earth Radius)
                # This represents the "average" height, stripping out perigee/apogee noise
                mean_altitude_km = semi_major_axis_km - EARTH_RADIUS_KM
                
                if mean_altitude_km < 0:
                    continue

                # 5. Extract other elements for context
                eccentricity = satellite.model.ecco
                is_circular = eccentricity < 0.01
                
                # Find closest Kp reading
                epoch_dt = row['epoch_datetime'].to_pydatetime()
                kp_value = self._find_closest_kp(epoch_dt, kp_df)
                
                results.append({
                    'Date': epoch_dt.date(),
                    'DateTime': epoch_dt,
                    'SemiMajorAxis': semi_major_axis_km,
                    'Altitude': mean_altitude_km,  # Storing Mean Alt instead of Instantaneous
                    'Eccentricity': eccentricity,
                    'Is_Circular': is_circular,
                    'Kp_Index': kp_value
                })
                
            except Exception as e:
                logger.warning(f"Failed to process TLE at index {idx}: {e}")
                continue
        
        if not results:
            return pd.DataFrame(columns=['Date', 'Altitude', 'Kp_Index', 'Daily_Drop'])
        
        # Create DataFrame
        result_df = pd.DataFrame(results)
        
        # Aggregate to daily values
        daily_df = result_df.groupby('Date').agg({
            'Altitude': 'mean',
            'Kp_Index': 'mean'
        }).reset_index()
        
        # Calculate daily altitude drop (negative change indicates decay)
        daily_df['Daily_Drop'] = daily_df['Altitude'].diff() * -1  # Positive = decay
        
        # First day has no drop (NaN -> 0)
        daily_df['Daily_Drop'] = daily_df['Daily_Drop'].fillna(0)
        
        logger.info(f"Generated {len(daily_df)} daily records for NORAD ID {norad_id}")
        
        return daily_df
    
    def _find_closest_kp(
        self, 
        target_dt: datetime, 
        kp_df: pd.DataFrame
    ) -> Optional[float]:
        """
        Find Kp index value closest to target datetime.
        
        Args:
            target_dt: Target datetime
            kp_df: DataFrame with Kp data (must have time_tag column)
            
        Returns:
            Closest Kp value, or None if no data
        """
        if kp_df.empty:
            return None
        
        try:
            # Ensure target is timezone-aware
            if target_dt.tzinfo is None:
                target_dt = target_dt.replace(tzinfo=timezone.utc)
            
            # Calculate time differences
            time_diffs = abs(kp_df['time_tag'] - target_dt)
            closest_idx = time_diffs.idxmin()
            
            return float(kp_df.loc[closest_idx, 'kp'])
            
        except Exception as e:
            logger.warning(f"Kp lookup failed: {e}")
            return None
    
    def generate_training_dataset(
        self, 
        norad_ids: Optional[List[int]] = None
    ) -> pd.DataFrame:
        """
        Generate combined dataset for all satellites in Golden Dataset.
        
        Args:
            norad_ids: List of NORAD IDs (default: Golden Dataset)
            
        Returns:
            Combined DataFrame with satellite identifier
        """
        if norad_ids is None:
            norad_ids = list(GOLDEN_DATASET.values())
        
        all_data = []
        
        for norad_id in norad_ids:
            df = self.propagate_with_weather(norad_id)
            if not df.empty:
                df['NORAD_ID'] = norad_id
                # Get satellite name
                sat_name = next(
                    (name for name, nid in GOLDEN_DATASET.items() if nid == norad_id),
                    f"NORAD_{norad_id}"
                )
                df['Satellite_Name'] = sat_name
                all_data.append(df)
        
        if not all_data:
            return pd.DataFrame()
        
        combined = pd.concat(all_data, ignore_index=True)
        logger.info(f"Generated training dataset with {len(combined)} records")
        
        return combined


# =============================================================================
# MAIN EXECUTION
# =============================================================================
def main():
    """
    Main execution demonstrating the ETL pipeline workflow.
    """
    print("=" * 60)
    print("SATELLITE ORBITAL DECAY ETL PIPELINE - DAY 1")
    print("=" * 60)
    
    # Database path
    DB_PATH = "satellite_data.db"
    
    # ==========================================================================
    # Step 1: Ingest Space Weather Data (Golden Epoch: 2014-Present)
    # ==========================================================================
    print("\n[1] Ingesting Space Weather Data (2014-Present)...")
    
    weather_ingestor = SpaceWeatherIngestor(db_path=DB_PATH)
    
    # Fetch historical Kp data from GFZ Potsdam (2014 to current year)
    try:
        total_kp = weather_ingestor.fetch_historical_kp(
            start_year=2014,
            end_year=datetime.now().year
        )
        print(f"    ✓ Stored {total_kp} Kp index records (2014-{datetime.now().year})")
    except Exception as e:
        print(f"    ✗ Failed to fetch historical Kp data: {e}")
    
    # ==========================================================================
    # Step 2: Space-Track TLE Ingestion (Requires credentials)
    # ==========================================================================
    print("\n[2] Space-Track TLE Ingestion...")
    print("    ⚠ Requires Space-Track.org credentials")
    print("    ⚠ Register free at: https://www.space-track.org/auth/createAccount")
    
    # Initialize TLE database table (even without data, so propagator can query it)
    # This creates the schema without requiring credentials
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.cursor()
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS tle_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                norad_id INTEGER NOT NULL,
                satellite_name TEXT,
                epoch_datetime TEXT NOT NULL,
                tle_line1 TEXT NOT NULL,
                tle_line2 TEXT NOT NULL,
                mean_motion REAL,
                eccentricity REAL,
                inclination REAL,
                bstar REAL,
                ingestion_timestamp TEXT DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(norad_id, epoch_datetime)
            )
        """)
        conn.commit()
    print("    ✓ TLE database schema initialized")
    
    # Space-Track credentials
    SPACETRACK_USER = "*******************"
    SPACETRACK_PASS = "************************"
    
    tle_ingestor = SpaceTrackIngestor(
        username=SPACETRACK_USER,
        password=SPACETRACK_PASS,
        db_path=DB_PATH
    )
    
    # ==========================================================================
    # GOLDEN EPOCH INGESTION (2014-Present)
    # ==========================================================================
    print("\n[2b] Golden Epoch TLE Ingestion (2014-Present)...")
    print("    ⚠ This may take several minutes (fetching 11+ years per satellite)")
    
    for name, norad_id in GOLDEN_DATASET.items():
        print(f"\n    📡 {name} (NORAD ID: {norad_id})")
        try:
            total = tle_ingestor.fetch_tle_golden_epoch(
                norad_id=norad_id,
                start_year=2014,
                force_refresh=False  # Use cache if available
            )
        except Exception as e:
            print(f"    ✗ Failed: {e}")
    
    # ==========================================================================
    # Step 3: Orbital Propagation Demo
    # ==========================================================================
    print("\n[3] Orbital Propagation...")
    
    propagator = OrbitalPropagator(db_path=DB_PATH)
    
    # Check if we have TLE data
    has_tle_data = False
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) FROM tle_history")
        count = cursor.fetchone()[0]
        has_tle_data = count > 0
    
    if not has_tle_data:
        print("    ⚠ No TLE data in database - run Step 2 with credentials first")
        print("    ⚠ Orbital propagation skipped")
    else:
        # Demo with stored data
        for name, norad_id in GOLDEN_DATASET.items():
            stored_tles = propagator.propagate_with_weather(norad_id)
            if not stored_tles.empty:
                print(f"\n    {name} Orbital History:")
                print(stored_tles.head(10).to_string(index=False))
    
    # ==========================================================================
    # Summary
    # ==========================================================================
    print("\n" + "=" * 60)
    print("ETL PIPELINE SUMMARY")
    print("=" * 60)
    print(f"Database: {DB_PATH}")
    print(f"Golden Dataset Satellites: {', '.join(GOLDEN_DATASET.keys())}")
    # print("\nNext Steps:")
    # print("  1. Register at Space-Track.org for TLE access")
    # print("  2. Add credentials to this script")
    # print("  3. Run full ingestion pipeline")
    # print("  4. Use propagate_with_weather() for ML training data")
    # print("=" * 60)


if __name__ == "__main__":
    main()
